### ISSUE TITLE
why I can't find "IFConnect.app"

### ISSUE THREAD

**Issue by Ryanpeng111** [brk-ozs11/IFConnect#2]
I downloaded the apps you shared, but when I look at my download folder, I only see a single file. Can you help me figure out what happened?
<img width="1032" alt="Screenshot 2024-09-22 at 9 16 03 PM" src="https://github.com/user-attachments/assets/13b64857-b06f-4740-838c-a795fe6cb8a7">
Is it my problem?

**Comment by brk-ozs11** [comment]
Hello, I just saw your message, sorry, of course, I would love to help you, you only downloaded the files in the repository, there is no application there, you need to download and unzip the zip file that says v1.0.0-intel-macOS in the Releases section to download it. Please write to me if you have any questions
